import 'package:flutter/foundation.dart';
import 'model.dart';

class CountryListController {
  final List<CountryCodes> countries = [
    CountryCodes(
      name: "Afghanistan",
      code: "+93",
      flagImagePath: 'packages/flutter_customs/assets/countries/af.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Åland",
      code: "+358",
      flagImagePath: 'packages/flutter_customs/assets/countries/ax.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Albania",
      code: "+355",
      flagImagePath: 'packages/flutter_customs/assets/countries/al.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Algeria",
      code: "+213",
      flagImagePath: 'packages/flutter_customs/assets/countries/dz.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "American Samoa",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/as.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Andorra",
      code: "+376",
      flagImagePath: 'packages/flutter_customs/assets/countries/ad.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Angola",
      code: "+244",
      flagImagePath: 'packages/flutter_customs/assets/countries/ao.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Anguilla",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/ai.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Antigua and Barbuda",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/ag.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Argentina",
      code: "+54",
      flagImagePath: 'packages/flutter_customs/assets/countries/ar.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Armenia",
      code: "+374",
      flagImagePath: 'packages/flutter_customs/assets/countries/am.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Aruba",
      code: "+297",
      flagImagePath: 'packages/flutter_customs/assets/countries/aw.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Ascension",
      code: "+247",
      flagImagePath: 'packages/flutter_customs/assets/countries/ac.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Australia",
      code: "+61",
      flagImagePath: 'packages/flutter_customs/assets/countries/au.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Austria",
      code: "+43",
      flagImagePath: 'packages/flutter_customs/assets/countries/at.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Azerbaijan",
      code: "+994",
      flagImagePath: 'packages/flutter_customs/assets/countries/az.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Bahamas",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/bs.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Bahrain",
      code: "+973",
      flagImagePath: 'packages/flutter_customs/assets/countries/bh.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Bangladesh",
      code: "+880",
      flagImagePath: 'packages/flutter_customs/assets/countries/bd.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Barbados",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/bb.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Belarus",
      code: "+375",
      flagImagePath: 'packages/flutter_customs/assets/countries/by.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Belgium",
      code: "+32",
      flagImagePath: 'packages/flutter_customs/assets/countries/be.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Belize",
      code: "+501",
      flagImagePath: 'packages/flutter_customs/assets/countries/bz.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Benin",
      code: "+229",
      flagImagePath: 'packages/flutter_customs/assets/countries/bj.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Bhutan",
      code: "+975",
      flagImagePath: 'packages/flutter_customs/assets/countries/bt.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Bolivia",
      code: "+591",
      flagImagePath: 'packages/flutter_customs/assets/countries/bo.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Bonaire",
      code: "+599",
      flagImagePath: 'packages/flutter_customs/assets/countries/bq.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Bosnia and Herzegovina",
      code: "+387",
      flagImagePath: 'packages/flutter_customs/assets/countries/ba.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Botswana",
      code: "+267",
      flagImagePath: 'packages/flutter_customs/assets/countries/bw.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Brazil",
      code: "+55",
      flagImagePath: 'packages/flutter_customs/assets/countries/br.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "British Indian Ocean Territory",
      code: "+246",
      flagImagePath: 'packages/flutter_customs/assets/countries/io.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "British Virgin Islands",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/vg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Brunei Darussalam",
      code: "+673",
      flagImagePath: 'packages/flutter_customs/assets/countries/bn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Bulgaria",
      code: "+359",
      flagImagePath: 'packages/flutter_customs/assets/countries/bg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Burkina Faso",
      code: "+226",
      flagImagePath: 'packages/flutter_customs/assets/countries/bf.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Burundi",
      code: "+257",
      flagImagePath: 'packages/flutter_customs/assets/countries/bi.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Cabo Verde",
      code: "+238",
      flagImagePath: 'packages/flutter_customs/assets/countries/cv.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Cambodia",
      code: "+855",
      flagImagePath: 'packages/flutter_customs/assets/countries/kh.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Cameroon",
      code: "+237",
      flagImagePath: 'packages/flutter_customs/assets/countries/cm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Canada",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/ca.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Cayman Islands",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/ky.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Central African Republic",
      code: "+236",
      flagImagePath: 'packages/flutter_customs/assets/countries/cf.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Chad",
      code: "+235",
      flagImagePath: 'packages/flutter_customs/assets/countries/td.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Chile",
      code: "+56",
      flagImagePath: 'packages/flutter_customs/assets/countries/cl.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "China",
      code: "+86",
      flagImagePath: 'packages/flutter_customs/assets/countries/cn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Christmas Island",
      code: "+61",
      flagImagePath: 'packages/flutter_customs/assets/countries/cx.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Cocos Islands",
      code: "+61",
      flagImagePath: 'packages/flutter_customs/assets/countries/cc.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Colombia",
      code: "+57",
      flagImagePath: 'packages/flutter_customs/assets/countries/co.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Comoros",
      code: "+269",
      flagImagePath: 'packages/flutter_customs/assets/countries/km.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Congo",
      code: "+242",
      flagImagePath: 'packages/flutter_customs/assets/countries/cg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Congo, The Democratic Republic of the Congo",
      code: "+243",
      flagImagePath: 'packages/flutter_customs/assets/countries/cd.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Cook Islands",
      code: "+682",
      flagImagePath: 'packages/flutter_customs/assets/countries/ck.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Costa Rica",
      code: "+506",
      flagImagePath: 'packages/flutter_customs/assets/countries/cr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Ivory Coast",
      code: "+225",
      flagImagePath: 'packages/flutter_customs/assets/countries/ci.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Croatia",
      code: "+385",
      flagImagePath: 'packages/flutter_customs/assets/countries/hr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Cuba",
      code: "+53",
      flagImagePath: 'packages/flutter_customs/assets/countries/cu.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Curaçao",
      code: "+599",
      flagImagePath: 'packages/flutter_customs/assets/countries/cw.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Cyprus",
      code: "+357",
      flagImagePath: 'packages/flutter_customs/assets/countries/cy.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Czech Republic",
      code: "+420",
      flagImagePath: 'packages/flutter_customs/assets/countries/cz.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Denmark",
      code: "+45",
      flagImagePath: 'packages/flutter_customs/assets/countries/dk.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Djibouti",
      code: "+253",
      flagImagePath: 'packages/flutter_customs/assets/countries/dj.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Dominica",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/dm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Dominican Republic",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/do.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Easter Island",
      code: "+56",
      flagImagePath: 'packages/flutter_customs/assets/countries/cl-ei.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Ecuador",
      code: "+593",
      flagImagePath: 'packages/flutter_customs/assets/countries/ec.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Egypt",
      code: "+20",
      flagImagePath: 'packages/flutter_customs/assets/countries/eg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "El Salvador",
      code: "+503",
      flagImagePath: 'packages/flutter_customs/assets/countries/sv.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Equatorial Guinea",
      code: "+240",
      flagImagePath: 'packages/flutter_customs/assets/countries/gq.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Eritrea",
      code: "+291",
      flagImagePath: 'packages/flutter_customs/assets/countries/er.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Estonia",
      code: "+372",
      flagImagePath: 'packages/flutter_customs/assets/countries/ee.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Eswatini",
      code: "+268",
      flagImagePath: 'packages/flutter_customs/assets/countries/sz.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Ethiopia",
      code: "+251",
      flagImagePath: 'packages/flutter_customs/assets/countries/et.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Falkland Islands",
      code: "+500",
      flagImagePath: 'packages/flutter_customs/assets/countries/fk.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Faroe Islands",
      code: "+298",
      flagImagePath: 'packages/flutter_customs/assets/countries/fo.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Fiji",
      code: "+679",
      flagImagePath: 'packages/flutter_customs/assets/countries/fj.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Finland",
      code: "+358",
      flagImagePath: 'packages/flutter_customs/assets/countries/fi.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "France",
      code: "+33",
      flagImagePath: 'packages/flutter_customs/assets/countries/fr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "French Guiana",
      code: "+594",
      flagImagePath: 'packages/flutter_customs/assets/countries/gf.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "French Polynesia",
      code: "+689",
      flagImagePath: 'packages/flutter_customs/assets/countries/pf.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Gabon",
      code: "+241",
      flagImagePath: 'packages/flutter_customs/assets/countries/ga.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Gambia",
      code: "+220",
      flagImagePath: 'packages/flutter_customs/assets/countries/gm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Georgia",
      code: "+995",
      flagImagePath: 'packages/flutter_customs/assets/countries/ge.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Germany",
      code: "+49",
      flagImagePath: 'packages/flutter_customs/assets/countries/de.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Ghana",
      code: "+233",
      flagImagePath: 'packages/flutter_customs/assets/countries/gh.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Gibraltar",
      code: "+350",
      flagImagePath: 'packages/flutter_customs/assets/countries/gi.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Greece",
      code: "+30",
      flagImagePath: 'packages/flutter_customs/assets/countries/gr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Greenland",
      code: "+299",
      flagImagePath: 'packages/flutter_customs/assets/countries/gl.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Grenada",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/gd.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Guadeloupe",
      code: "+590",
      flagImagePath: 'packages/flutter_customs/assets/countries/gp.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Guam",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/gu.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Guatemala",
      code: "+502",
      flagImagePath: 'packages/flutter_customs/assets/countries/gt.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Guernsey",
      code: "+44",
      flagImagePath: 'packages/flutter_customs/assets/countries/gg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Guinea",
      code: "+224",
      flagImagePath: 'packages/flutter_customs/assets/countries/gn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Guinea-Bissau",
      code: "+245",
      flagImagePath: 'packages/flutter_customs/assets/countries/gw.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Guyana",
      code: "+592",
      flagImagePath: 'packages/flutter_customs/assets/countries/gy.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Haiti",
      code: "+509",
      flagImagePath: 'packages/flutter_customs/assets/countries/ht.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Honduras",
      code: "+504",
      flagImagePath: 'packages/flutter_customs/assets/countries/hn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Hong Kong",
      code: "+852",
      flagImagePath: 'packages/flutter_customs/assets/countries/hk.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Hungary",
      code: "+36",
      flagImagePath: 'packages/flutter_customs/assets/countries/hu.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Iceland",
      code: "+354",
      flagImagePath: 'packages/flutter_customs/assets/countries/is.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "India",
      code: "+91",
      flagImagePath: 'packages/flutter_customs/assets/countries/in.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Indonesia",
      code: "+62",
      flagImagePath: 'packages/flutter_customs/assets/countries/id.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Iran",
      code: "+98",
      flagImagePath: 'packages/flutter_customs/assets/countries/ir.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Iraq",
      code: "+964",
      flagImagePath: 'packages/flutter_customs/assets/countries/iq.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Ireland",
      code: "+353",
      flagImagePath: 'packages/flutter_customs/assets/countries/ie.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Isle of Man",
      code: "+44",
      flagImagePath: 'packages/flutter_customs/assets/countries/im.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Israel",
      code: "+972",
      flagImagePath: 'packages/flutter_customs/assets/countries/il.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Italy",
      code: "+39",
      flagImagePath: 'packages/flutter_customs/assets/countries/it.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Jamaica",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/jm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Japan",
      code: "+81",
      flagImagePath: 'packages/flutter_customs/assets/countries/jp.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Jersey",
      code: "+44",
      flagImagePath: 'packages/flutter_customs/assets/countries/je.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Jordan",
      code: "+962",
      flagImagePath: 'packages/flutter_customs/assets/countries/jo.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Kazakhstan",
      code: "+7",
      flagImagePath: 'packages/flutter_customs/assets/countries/kz.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Kenya",
      code: "+254",
      flagImagePath: 'packages/flutter_customs/assets/countries/ke.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Kiribati",
      code: "+686",
      flagImagePath: 'packages/flutter_customs/assets/countries/ki.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Kuwait",
      code: "+965",
      flagImagePath: 'packages/flutter_customs/assets/countries/kw.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Kyrgyzstan",
      code: "+996",
      flagImagePath: 'packages/flutter_customs/assets/countries/kg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Laos",
      code: "+856",
      flagImagePath: 'packages/flutter_customs/assets/countries/la.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Latvia",
      code: "+371",
      flagImagePath: 'packages/flutter_customs/assets/countries/lv.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Lebanon",
      code: "+961",
      flagImagePath: 'packages/flutter_customs/assets/countries/lb.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Lesotho",
      code: "+266",
      flagImagePath: 'packages/flutter_customs/assets/countries/lh.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Liberia",
      code: "+231",
      flagImagePath: 'packages/flutter_customs/assets/countries/lr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Libya",
      code: "+218",
      flagImagePath: 'packages/flutter_customs/assets/countries/ly.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Liechtenstein",
      code: "+423",
      flagImagePath: 'packages/flutter_customs/assets/countries/li.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Lithuania",
      code: "+370",
      flagImagePath: 'packages/flutter_customs/assets/countries/lt.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Luxembourg",
      code: "+352",
      flagImagePath: 'packages/flutter_customs/assets/countries/lu.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Macao",
      code: "+853",
      flagImagePath: 'packages/flutter_customs/assets/countries/mo.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Madagascar",
      code: "+261",
      flagImagePath: 'packages/flutter_customs/assets/countries/mg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Malawi",
      code: "+265",
      flagImagePath: 'packages/flutter_customs/assets/countries/mw.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Malaysia",
      code: "+60",
      flagImagePath: 'packages/flutter_customs/assets/countries/my.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Maldives",
      code: "+960",
      flagImagePath: 'packages/flutter_customs/assets/countries/mv.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Mali",
      code: "+223",
      flagImagePath: 'packages/flutter_customs/assets/countries/ml.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Malta",
      code: "+356",
      flagImagePath: 'packages/flutter_customs/assets/countries/mt.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Marshall Islands",
      code: "+692",
      flagImagePath: 'packages/flutter_customs/assets/countries/mh.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Martinique",
      code: "+596",
      flagImagePath: 'packages/flutter_customs/assets/countries/mq.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Mauritania",
      code: "+222",
      flagImagePath: 'packages/flutter_customs/assets/countries/mr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Mauritius",
      code: "+230",
      flagImagePath: 'packages/flutter_customs/assets/countries/mu.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Mayotte",
      code: "+262",
      flagImagePath: 'packages/flutter_customs/assets/countries/yt.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Mexico",
      code: "+52",
      flagImagePath: 'packages/flutter_customs/assets/countries/mx.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Micronesia, Federated States of",
      code: "+691",
      flagImagePath: 'packages/flutter_customs/assets/countries/fm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Moldova",
      code: "+373",
      flagImagePath: 'packages/flutter_customs/assets/countries/md.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Monaco",
      code: "+377",
      flagImagePath: 'packages/flutter_customs/assets/countries/mc.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Mongolia",
      code: "+976",
      flagImagePath: 'packages/flutter_customs/assets/countries/mn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Montenegro",
      code: "+382",
      flagImagePath: 'packages/flutter_customs/assets/countries/me.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Montserrat",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/ms.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Morocco",
      code: "+212",
      flagImagePath: 'packages/flutter_customs/assets/countries/ma.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Mozambique",
      code: "+258",
      flagImagePath: 'packages/flutter_customs/assets/countries/mz.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Myanmar",
      code: "+95",
      flagImagePath: 'packages/flutter_customs/assets/countries/mm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Namibia",
      code: "+264",
      flagImagePath: 'packages/flutter_customs/assets/countries/na.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Nauru",
      code: "+674",
      flagImagePath: 'packages/flutter_customs/assets/countries/nr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Nepal",
      code: "+977",
      flagImagePath: 'packages/flutter_customs/assets/countries/np.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Netherlands",
      code: "+31",
      flagImagePath: 'packages/flutter_customs/assets/countries/nl.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "New Caledonia",
      code: "+687",
      flagImagePath: 'packages/flutter_customs/assets/countries/nc.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "New Zealand",
      code: "+64",
      flagImagePath: 'packages/flutter_customs/assets/countries/nz.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Nicaragua",
      code: "+505",
      flagImagePath: 'packages/flutter_customs/assets/countries/ni.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Niger",
      code: "+227",
      flagImagePath: 'packages/flutter_customs/assets/countries/ne.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Nigeria",
      code: "+234",
      flagImagePath: 'packages/flutter_customs/assets/countries/ng.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Niue",
      code: "+683",
      flagImagePath: 'packages/flutter_customs/assets/countries/nu.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Norfolk Island",
      code: "+672",
      flagImagePath: 'packages/flutter_customs/assets/countries/nf.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "North Macedonia",
      code: "+389",
      flagImagePath: 'packages/flutter_customs/assets/countries/mk.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Northern Cyprus",
      code: "+90",
      flagImagePath: 'packages/flutter_customs/assets/countries/cy-nc.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Northern Ireland",
      code: "+44",
      flagImagePath: 'packages/flutter_customs/assets/countries/gb-nir.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Northern Mariana Islands",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/mp.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Norway",
      code: "+47",
      flagImagePath: 'packages/flutter_customs/assets/countries/no.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Oman",
      code: "+968",
      flagImagePath: 'packages/flutter_customs/assets/countries/om.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Pakistan",
      code: "+92",
      flagImagePath: 'packages/flutter_customs/assets/countries/pk.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Palau",
      code: "+680",
      flagImagePath: 'packages/flutter_customs/assets/countries/pw.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Palestine",
      code: "+970",
      flagImagePath: 'packages/flutter_customs/assets/countries/ps.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Panama",
      code: "+507",
      flagImagePath: 'packages/flutter_customs/assets/countries/pa.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Papua New Guinea",
      code: "+675",
      flagImagePath: 'packages/flutter_customs/assets/countries/pg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Paraguay",
      code: "+595",
      flagImagePath: 'packages/flutter_customs/assets/countries/py.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Peru",
      code: "+51",
      flagImagePath: 'packages/flutter_customs/assets/countries/pe.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Philippines",
      code: "+63",
      flagImagePath: 'packages/flutter_customs/assets/countries/ph.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Pitcairn Islands",
      code: "+64",
      flagImagePath: 'packages/flutter_customs/assets/countries/pn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Poland",
      code: "+48",
      flagImagePath: 'packages/flutter_customs/assets/countries/pl.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Portugal",
      code: "+351",
      flagImagePath: 'packages/flutter_customs/assets/countries/pt.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Puerto Rico",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/pr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Qatar",
      code: "+974",
      flagImagePath: 'packages/flutter_customs/assets/countries/qa.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Réunion",
      code: "+262",
      flagImagePath: 'packages/flutter_customs/assets/countries/re.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Romania",
      code: "+40",
      flagImagePath: 'packages/flutter_customs/assets/countries/ro.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Russia",
      code: "+7",
      flagImagePath: 'packages/flutter_customs/assets/countries/ru.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Rwanda",
      code: "+250",
      flagImagePath: 'packages/flutter_customs/assets/countries/rw.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Saba",
      code: "+599",
      flagImagePath: 'packages/flutter_customs/assets/countries/sx-s.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Saint Barthélemy",
      code: "+590",
      flagImagePath: 'packages/flutter_customs/assets/countries/bl.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Saint Helena",
      code: "+290",
      flagImagePath: 'packages/flutter_customs/assets/countries/sh.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Saint Kitts and Nevis",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/kn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Saint Lucia",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/lc.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Saint Martin",
      code: "+590",
      flagImagePath: 'packages/flutter_customs/assets/countries/mf.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Saint Pierre and Miquelon",
      code: "+508",
      flagImagePath: 'packages/flutter_customs/assets/countries/pm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Saint Vincent and the Grenadines",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/vc.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Samoa",
      code: "+685",
      flagImagePath: 'packages/flutter_customs/assets/countries/ws.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "San Marino",
      code: "+378",
      flagImagePath: 'packages/flutter_customs/assets/countries/sm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Sao Tome and Principe",
      code: "+239",
      flagImagePath: 'packages/flutter_customs/assets/countries/st.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Saudi Arabia",
      code: "+966",
      flagImagePath: 'packages/flutter_customs/assets/countries/sa.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Senegal",
      code: "+221",
      flagImagePath: 'packages/flutter_customs/assets/countries/sn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Serbia",
      code: "+381",
      flagImagePath: 'packages/flutter_customs/assets/countries/rs.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Seychelles",
      code: "+248",
      flagImagePath: 'packages/flutter_customs/assets/countries/sc.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Sierra Leone",
      code: "+232",
      flagImagePath: 'packages/flutter_customs/assets/countries/sl.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Singapore",
      code: "+65",
      flagImagePath: 'packages/flutter_customs/assets/countries/sg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Sint Eustatius",
      code: "+599",
      flagImagePath: 'packages/flutter_customs/assets/countries/sx.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Sint Maarten",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/sx-m.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Slovakia",
      code: "+421",
      flagImagePath: 'packages/flutter_customs/assets/countries/sk.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Slovenia",
      code: "+386",
      flagImagePath: 'packages/flutter_customs/assets/countries/si.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Solomon Islands",
      code: "+677",
      flagImagePath: 'packages/flutter_customs/assets/countries/sb.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Somalia",
      code: "+252",
      flagImagePath: 'packages/flutter_customs/assets/countries/so.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "South Africa",
      code: "+27",
      flagImagePath: 'packages/flutter_customs/assets/countries/za.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "South Georgia and the South Sandwich Islands",
      code: "+500",
      flagImagePath: 'packages/flutter_customs/assets/countries/gs.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "South Ossetia",
      code: "+7",
      flagImagePath: 'packages/flutter_customs/assets/countries/os.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "South Sudan",
      code: "+211",
      flagImagePath: 'packages/flutter_customs/assets/countries/ss.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Spain",
      code: "+34",
      flagImagePath: 'packages/flutter_customs/assets/countries/es.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Sri Lanka",
      code: "+94",
      flagImagePath: 'packages/flutter_customs/assets/countries/lk.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Sudan",
      code: "+249",
      flagImagePath: 'packages/flutter_customs/assets/countries/sd.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Suriname",
      code: "+597",
      flagImagePath: 'packages/flutter_customs/assets/countries/sr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Svalbard",
      code: "+47",
      flagImagePath: 'packages/flutter_customs/assets/countries/sj.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Sweden",
      code: "+46",
      flagImagePath: 'packages/flutter_customs/assets/countries/se.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Switzerland",
      code: "+41",
      flagImagePath: 'packages/flutter_customs/assets/countries/ch.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Syria",
      code: "+963",
      flagImagePath: 'packages/flutter_customs/assets/countries/sy.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Taiwan",
      code: "+886",
      flagImagePath: 'packages/flutter_customs/assets/countries/tw.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Tajikistan",
      code: "+992",
      flagImagePath: 'packages/flutter_customs/assets/countries/tj.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Tanzania",
      code: "+255",
      flagImagePath: 'packages/flutter_customs/assets/countries/tz.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Thailand",
      code: "+66",
      flagImagePath: 'packages/flutter_customs/assets/countries/th.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Timor-Leste",
      code: "+670",
      flagImagePath: 'packages/flutter_customs/assets/countries/tl.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Togo",
      code: "+228",
      flagImagePath: 'packages/flutter_customs/assets/countries/tg.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Tokelau",
      code: "+690",
      flagImagePath: 'packages/flutter_customs/assets/countries/tk.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Tonga",
      code: "+676",
      flagImagePath: 'packages/flutter_customs/assets/countries/to.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Trinidad and Tobago",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/tt.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Tunisia",
      code: "+216",
      flagImagePath: 'packages/flutter_customs/assets/countries/tn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Turkey",
      code: "+90",
      flagImagePath: 'packages/flutter_customs/assets/countries/tr.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Turkmenistan",
      code: "+993",
      flagImagePath: 'packages/flutter_customs/assets/countries/tm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Turks and Caicos Islands",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/tc.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Tuvalu",
      code: "+688",
      flagImagePath: 'packages/flutter_customs/assets/countries/tv.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Uganda",
      code: "+256",
      flagImagePath: 'packages/flutter_customs/assets/countries/ug.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Ukraine",
      code: "+380",
      flagImagePath: 'packages/flutter_customs/assets/countries/ua.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "United Arab Emirates",
      code: "+971",
      flagImagePath: 'packages/flutter_customs/assets/countries/ae.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "United Kingdom",
      code: "+44",
      flagImagePath: 'packages/flutter_customs/assets/countries/gb.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "United States",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/us.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Uruguay",
      code: "+598",
      flagImagePath: 'packages/flutter_customs/assets/countries/uy.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Uzbekistan",
      code: "+998",
      flagImagePath: 'packages/flutter_customs/assets/countries/uz.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Vanuatu",
      code: "+678",
      flagImagePath: 'packages/flutter_customs/assets/countries/vu.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Venezuela",
      code: "+58",
      flagImagePath: 'packages/flutter_customs/assets/countries/ve.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Vietnam",
      code: "+84",
      flagImagePath: 'packages/flutter_customs/assets/countries/vn.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Wake Island",
      code: "+1",
      flagImagePath: 'packages/flutter_customs/assets/countries/wk.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Wallis and Futuna",
      code: "+681",
      flagImagePath: 'packages/flutter_customs/assets/countries/wf.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Yemen",
      code: "+967",
      flagImagePath: 'packages/flutter_customs/assets/countries/ye.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Zambia",
      code: "+260",
      flagImagePath: 'packages/flutter_customs/assets/countries/zm.svg',
      phoneformat: '### #######',
    ),
    CountryCodes(
      name: "Zimbabwe",
      code: "+263",
      flagImagePath: 'packages/flutter_customs/assets/countries/zw.svg',
      phoneformat: '### #######',
    ),
  ];

  late String selectedCountryName;
  late String selectedCountryCode;
  late String selectedCountryFlagPath;
  late String selectedCountryFormat;

  void initializeSelectedCountry() {
    selectedCountryName = countries.first.name;
    selectedCountryCode = countries.first.code;
    selectedCountryFlagPath = countries.first.flagImagePath;
    selectedCountryFormat = countries.first.phoneformat;
  }

  void checkForMissingFlags(List<String> websiteCountries) {
    List<String> existingCountries =
        countries.map((country) => country.name).toList();

    for (var country in websiteCountries) {
      if (!existingCountries.contains(country)) {
        if (kDebugMode) {
          print('Missing flag for: $country');
        }
      }
    }
  }

  void checkForDuplicateFlags() {
    final List<String> flagPaths =
        countries.map((country) => country.flagImagePath).toList();
    final Set<String> uniqueFlags = <String>{};

    for (var path in flagPaths) {
      if (!uniqueFlags.add(path)) {
        if (kDebugMode) {
          print('Duplicate flag found: $path');
        }
      }
    }
  }
}
